name: Handle Release
on:
  release:
    types: [published]
    # types: [created,edited,published]
jobs:
  generate:
    name: create release-artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.9.x]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: init Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: tests and package
        uses: coactions/setup-xvfb@v1
        with:
          run: |
            npm install
            npm run package
      - name: upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.vsix'